# coding: utf-8

"""
    Guardrails API

    Guardrails CRUD API

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LLMResource(str, Enum):
    """
    LLMResource
    """

    """
    allowed enum values
    """
    OPENAI_DOT_COMPLETION_DOT_CREATE = 'openai.Completion.create'
    OPENAI_DOT_COMPLETIONS_DOT_CREATE = 'openai.completions.create'
    OPENAI_DOT_CHAT_COMPLETION_DOT_CREATE = 'openai.ChatCompletion.create'
    OPENAI_DOT_CHAT_DOT_COMPLETIONS_DOT_CREATE = 'openai.chat.completions.create'
    OPENAI_DOT_COMPLETION_DOT_ACREATE = 'openai.Completion.acreate'
    OPENAI_DOT_CHAT_COMPLETION_DOT_ACREATE = 'openai.ChatCompletion.acreate'
    LITELLM_DOT_COMPLETION = 'litellm.completion'
    LITELLM_DOT_ACOMPLETION = 'litellm.acompletion'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LLMResource from a JSON string"""
        return cls(json.loads(json_str))


