# coding: utf-8

"""
    Guardrails API

    Guardrails CRUD API

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from guardrails_api_client.models.llm_resource import LLMResource
from typing import Set
from typing_extensions import Self

class ValidatePayload(BaseModel):
    """
    ValidatePayload
    """ # noqa: E501
    llm_output: Optional[Any] = Field(default=None, description="The LLM output as a string or the input prompts for the LLM", alias="llmOutput")
    num_reasks: Optional[Any] = Field(default=None, description="An override for the number of re-asks to perform", alias="numReasks")
    prompt_params: Optional[Dict[str, Any]] = Field(default=None, description="additional params for llm prompts", alias="promptParams")
    llm_api: Optional[LLMResource] = Field(default=None, alias="llmApi")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["llmOutput", "numReasks", "promptParams", "llmApi"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidatePayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if llm_output (nullable) is None
        # and model_fields_set contains the field
        if self.llm_output is None and "llm_output" in self.model_fields_set:
            _dict['llmOutput'] = None

        # set to None if num_reasks (nullable) is None
        # and model_fields_set contains the field
        if self.num_reasks is None and "num_reasks" in self.model_fields_set:
            _dict['numReasks'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidatePayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "llmOutput": obj.get("llmOutput"),
            "numReasks": obj.get("numReasks"),
            "llmApi": obj.get("llmApi")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


